#!/usr/bin/env python
'''
MTI Constants

@author: Stuart Baker
'''

MTI_INITIALIZATION_COMPLETE         = 0x0100
MTI_VERIFY_NODE_ID_ADDRESSED        = 0x0488
MTI_VERIFY_NODE_ID_GLOBAL           = 0x0490
MTI_VERIFY_NODE_ID_NUMBER           = 0x0170
MTI_OPTIONAL_INTERACTION_REJECTED   = 0x0068
MTI_TERMINATE_DUE_TO_ERROR          = 0x00A8

MTI_PROTOCOL_SUPPORT_INQUIRY        = 0x0828
MTI_PROTOCOL_SUPPORT_REPLY          = 0x0668

MTI_IDENTIFY_CONSUMER               = 0x08F4
MTI_CONSUMER_RANGE_IDENTIFIED       = 0x04A4
MTI_CONSUMER_IDENTIFIED_UNKNOWN     = 0x04C7
MTI_CONSUMER_IDENTIFIED_VALID       = 0x04C4
MTI_CONSUMER_IDENTIFIED_INVALID     = 0x04C5
MTI_CONSUMER_IDENTIFIED_RESERVED    = 0x04C6
MTI_IDENTIFY_PRODUCER               = 0x0914
MTI_PRODUCER_RANGE_IDENTIFIED       = 0x0524
MTI_PRODUCER_IDENTIFIED_UNKNOWN     = 0x0547
MTI_PRODUCER_IDENTIFIED_VALID       = 0x0544
MTI_PRODUCER_IDENTIFIED_INVALID     = 0x0545
MTI_PRODUCER_IDENTIFIED_RESERVED    = 0x0546
MTI_IDENTIFY_EVENTS_ADDRESSED       = 0x0968
MTI_IDENTIFY_EVENTS_GLOBAL          = 0x0970
MTI_LEARN_EVENT                     = 0x0594
MTI_EVENT_REPORT                    = 0x05B4

MTI_TRACTION_CONTROL_COMMAND        = 0x05EB
MTI_TRACTION_CONTROL_REPLY          = 0x01E9
MTI_TRACTION_PROXY_COMMAND          = 0x05EA
MTI_TRACTION_PROXY_REPLY            = 0x01E8

MTI_XPRESSNET                       = 0x0820

MTI_REMOTE_BUTTON_REQUEST           = 0x0948
MTI_REMOTE_BUTTON_REPLY             = 0x0549

MTI_SIMPLE_TRAIN_NODE_IDENT_REQUEST = 0x0DA8
MTI_SIMPLE_TRAIN_NODE_IDENT_REPLY   = 0x0A08

MTI_SIMPLE_NODE_IDENT_REQUEST       = 0x0DE8
MTI_SIMPLE_NODE_IDENT_REPLY         = 0x0A08

MTI_DATAGRAM                        = 0x1C48
MTI_DATAGRAM_RECEIVED_OK            = 0x0A28
MTI_DATAGRAM_REJECTED               = 0x0A48

MTI_STREAM_INITIATE_REQUEST         = 0x0CC8
MTI_STREAM_INITIATE_REPLY           = 0x0868
MTI_STREAM_DATA_SEND                = 0x1F88
MTI_STREAM_DATA_PROCEED             = 0x0888
MTI_STREAM_DATA_COMPLETE            = 0x08A8

